# Generated by Django 2.2.3 on 2019-07-16 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ジャンル名')),
                ('basic_rate', models.IntegerField(verbose_name='基本料金')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending_hour', models.IntegerField(verbose_name='受講時間')),
                ('attending_date', models.DateField(verbose_name='受講日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account', verbose_name='受講者')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.Genre', verbose_name='ジャンル')),
            ],
        ),
    ]
